//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinsApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinsApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All coins.
        /// </summary>
        internal static string AllCoins {
            get {
                return ResourceManager.GetString("AllCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 coins.
        /// </summary>
        internal static string BtnTop10 {
            get {
                return ResourceManager.GetString("BtnTop10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 24h.
        /// </summary>
        internal static string Change24hColumn {
            get {
                return ResourceManager.GetString("Change24hColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change7d.
        /// </summary>
        internal static string Change7dColumn {
            get {
                return ResourceManager.GetString("Change7dColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap.
        /// </summary>
        internal static string MarketCapColumn {
            get {
                return ResourceManager.GetString("MarketCapColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string PreviousButton {
            get {
                return ResourceManager.GetString("PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (USD).
        /// </summary>
        internal static string PriceColumn {
            get {
                return ResourceManager.GetString("PriceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter coin name....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string SymbolColumn {
            get {
                return ResourceManager.GetString("SymbolColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 Cryptocurrencies.
        /// </summary>
        internal static string Top10Cryptocurrencies {
            get {
                return ResourceManager.GetString("Top10Cryptocurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change 1h.
        /// </summary>
        internal static string Сhange1hColumn {
            get {
                return ResourceManager.GetString("Сhange1hColumn", resourceCulture);
            }
        }
    }
}
